version: '3'
services:
  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: 'test'
      MYSQL_PASS: 'password'
    image: "mysql:5.7"
    restart: always
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/my.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d/"
    ports:
      - "3307:3306"
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/data:/data:rw
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    command:
      - sh
      - -c
      - >
        rabbitmq-server&
        sleep 15&&
        rabbitmqctl add_vhost backend&&
        rabbitmqctl add_vhost broker&&
        rabbitmqctl add_user root root&&
        rabbitmqctl set_user_tags root administrator&&
        rabbitmqctl set_permissions -p backend root ".*" ".*" ".*"&&
        rabbitmqctl set_permissions -p broker root ".*" ".*" ".*"&&
        wait
  web:
    container_name: python-3.8
    build: .
    restart: always
    ports:
      - "8080:8000"
    depends_on:
      - db
      - rabbitmq
      - redis