FROM python:3.8-buster

ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app
COPY requirements.txt ./
COPY ops/dev/sources.list /etc/apt/sources.list
RUN  rm -Rf /var/lib/apt/lists/* && apt-get update && \
     pip3 config set global.index-url https://pypi.douban.com/simple/ && pip3 install --no-cache-dir -r requirements.txt
