version: '2'
services:
    db:
      container_name: postgres-db
      image: 'mysql:5.7'
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: django-test
        TZ: 'Asia/Shanghai'
      restart: always
      volumes:
        - 'postgres_data:/var/lib/mysql'
      ports:
        - "3307:3306"
    redis:
      restart: always
      image: redis:5.0.0
      container_name: redis-db
      command: redis-server --requirepass password
      ports:
        - "6379:6379"
    rabbitmq:
      image: rabbitmq:3.7
      ports:
        - "15673:15672"
      restart: always
      command:
        - sh
        - -c
        - >
          rabbitmq-server&
          sleep 15&&
          rabbitmqctl add_vhost backend&&
          rabbitmqctl add_vhost broker&&
          rabbitmqctl add_user root root&&
          rabbitmqctl set_user_tags root administrator&&
          rabbitmqctl set_permissions -p backend root ".*" ".*" ".*"&&
          rabbitmqctl set_permissions -p broker root ".*" ".*" ".*"&&
          wait
    web:
      container_name: python-3.6
      build:
        context: ../..
        dockerfile: Dockerfile-dev
      restart: always
      ports:
        - "5000:8000"
        - "8001:8001"
      depends_on:
        - db
        - rabbitmq
volumes:
  postgres_data: