# Generated by Django 3.2.11 on 2022-01-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=1642944846, verbose_name='创建时间')),
                ('updated_at', models.IntegerField(default=1642944846, verbose_name='修改时间')),
                ('format_created_at', models.DateTimeField(auto_now=True, verbose_name='格式化时间')),
                ('format_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='格式化修改时间')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('email', models.CharField(max_length=200, verbose_name='邮箱')),
                ('message', models.TextField(verbose_name='留言')),
                ('blog_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='博客地址')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
