# Generated by Django 3.2.11 on 2022-01-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=1643269726, verbose_name='创建时间')),
                ('updated_at', models.IntegerField(default=1643269726, verbose_name='修改时间')),
                ('format_created_at', models.DateTimeField(auto_now=True, verbose_name='格式化时间')),
                ('format_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='格式化修改时间')),
                ('task_name', models.CharField(max_length=200, verbose_name='名称')),
                ('type', models.CharField(choices=[(0, 'async task'), (1, 'timed task'), (-1, 'unknown task')], default='unknown task', max_length=20, verbose_name='状态')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.IntegerField(default=1643269726, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.IntegerField(default=1643269726, verbose_name='修改时间'),
        ),
    ]
