version: '3'

services:
  rabbit:
    image: rabbitmq:3.8-management
    hostname: rabbit1  # rabbit存储数据的标识，方便后续查找数据
    container_name: rabbit1
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./data:/var/lib/rabbitmq