version: '2'
services:
  mysql:
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: 'test'
      MYSQL_PASS: 'password'
    image: "mysql:5.7"
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
      - "./mysql.cnf:/etc/my.cnf"
      - "./init.sql:/docker-entrypoint-initdb.d/"
    ports:
      - "3307:3306"