name: 'teiba sign for web'

on:
  schedule:
    - cron: '0 6-18/12 * * *'
  workflow_dispatch:
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v2.3.0
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        env:
          STOKEN: ${{ secrets.TIEBA_STOKEN }}
          BDUSS: ${{ secrets.TIEBA_BDUSS }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 'sign'
        run: python tieba_web.py